### ISSUE TITLE
User engagement tracking

### ISSUE THREAD

**Issue by yesenia-gtz** [CA-Data/Open-Data-Portal#114]
ISSUE LEAD: @hamiltonryan 

Q3 OKR: 20% increase in product engagement and adoption of open data by State entities after launch

Tasks:
- [x] Draft rating questions for engagement
- [x] Ensure same test for current portal and MVP are used for two separate test groups (data.ca.gov and lab.data.ca.gov)
- [x] Incorporate A/B tests for Topics, Filters, Preview links, and API links
- [x] Build out tests in Usertesting
- [x] Launch tests
- [x] Synthesize results
- [x] build slide deck with results 
- [x] Document insights in Coda
- [x] Share insights with team
